name: Build and Push Docker Images (DIXY)

on:
  push:
    branches: [main, cloud, analytics]
  workflow_dispatch:
    inputs:
      version:
        description: "Version (optional)"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        db-type: [postgresql, mysql]

    steps:
      - uses: actions/checkout@v3

      - name: Set version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Generate tags
        run: |
          tags="ghcr.io/${{ github.repository_owner }}/umami:${{ matrix.db-type }}-${VERSION}"
          tags="$tags,ghcr.io/${{ github.repository_owner }}/umami:${{ matrix.db-type }}-latest"

          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            minor="${VERSION%.*}"
            major="${VERSION%%.*}"
            tags="$tags,ghcr.io/${{ github.repository_owner }}/umami:${{ matrix.db-type }}-$minor"
            tags="$tags,ghcr.io/${{ github.repository_owner }}/umami:${{ matrix.db-type }}-$major"
          fi

          echo "TAGS=$tags" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          build-args: |
            DATABASE_TYPE=${{ matrix.db-type }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAGS }}
