name: Build and Push Docker Images (GHCR)

on:
  push:
    branches:
      - main
      - cloud
      - analytics
  workflow_dispatch:
    inputs:
      version:
        description: "Version (optional)"
        required: false
        type: string

jobs:
  build:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db-type: [postgresql, mysql]

    steps:
      - uses: actions/checkout@v3

      - name: Set version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Generate tags
        run: |
          echo "TAG_PATCH=${{ matrix.db-type }}-${VERSION}" >> $GITHUB_ENV
          echo "TAG_MINOR=${{ matrix.db-type }}-$(echo ${VERSION} | cut -d. -f1,2)" >> $GITHUB_ENV || true
          echo "TAG_MAJOR=${{ matrix.db-type }}-$(echo ${VERSION} | cut -d. -f1)" >> $GITHUB_ENV || true
          echo "TAG_LATEST=${{ matrix.db-type }}-latest" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} 

      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            DATABASE_TYPE=${{ matrix.db-type }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/umami:${{ env.TAG_PATCH }}
            ghcr.io/${{ github.repository_owner }}/umami:${{ env.TAG_MINOR }}
            ghcr.io/${{ github.repository_owner }}/umami:${{ env.TAG_MAJOR }}
            ghcr.io/${{ github.repository_owner }}/umami:${{ env.TAG_LATEST }}